### ISSUE TITLE
'Word2Vec' object has no attribute 'infer_vector'

### ISSUE THREAD

**Issue by crowoy** [jhlau/doc2vec#18]
I've cloned the repo, downloaded the pre-trained Wikipedia model, and installed Gensim via `pip install git+https://github.com/jhlau/gensim`.

Then I pasted the model into the `toy_data` directory and changed the model line in the file to: `model="toy_data/word2vec.bin"`

However, when I run `infer_test.py` I get the following error:

```
Traceback (most recent call last):
  File "infer_test.py", line 25, in <module>
    output.write( " ".join([str(x) for x in m.infer_vector(d, alpha=start_alpha, steps=infer_epoch)]) + "\n" )
AttributeError: 'Word2Vec' object has no attribute 'infer_vector'
```

**Comment by jhlau** [comment]
Looks like it's probably not reading from my forked version of gensim. Can you test if you can call infer_test manually with an interactive python session?

**Comment by jhlau** [comment]
Weird, I just tried doing a fresh install (with virtualenv) and have no problems. Your gensim version seems to be right too (0.12.4), so I am not sure why this is happening.

Can you try create a new virtualenv, install gensim like you did before and try again?

**Comment by crowoy** [comment]
So I've run the following:

```
$ virtualenv env
$ source env/bin/activate
(env) $ pip install git+https://github.com/jhlau/gensim
(env) $ python
>>> import gensim.models as g
>>> model = g.Doc2Vec.load("toy_data/word2vec.bin")
>>> model.infer_vector("this is a test".split(), alpha=0.01, steps=1000)
```

And is still outputs:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model.infer_vector("this is a test".split(), alpha=0.01, steps=1000)
AttributeError: 'Word2Vec' object has no attribute 'infer_vector'
```

**Comment by jhlau** [comment]
Yea this really beats me. The train_model.py loads pre-trained embeddings (standard gensim) and it won't work if you use the canonical gensim, so it looks like your gensim version is right but somehow it doesn't see infer_vector function isn't working...

**Comment by rafiqhasan** [comment]
Any fix on this yet ? We are facing a similar issue.

**Comment by Abhimanyu100** [comment]
I am facing this same issue with doc2vec. My code run fine on Google Cloab, but getting an error while running locally on my own system.
`
AttributeError: 'NumpyArrayWrapper' object has no attribute 'infer_vector'`

**Comment by Saatvik-droid** [comment]
Did anyone solved this?

**Comment by Saatvik-droid** [comment]
Running and saving my own model with `train_model.py` it can use `infer_vector`.
