### ISSUE TITLE
AttributeError: Can't get attribute 'DocvecsArray'

### ISSUE THREAD

**Issue by bruceschek** [jhlau/doc2vec#35]
Any advice on the following will be greatly appreciated.  

I am attempting to load one of the pretrained models, via this code:

    from gensim.models.doc2vec import Doc2Vec, TaggedDocument
    model = Doc2Vec.load('doc2vec.bin')

The stack trace and error:

Traceback (most recent call last):
  File "/Users/bruceschechter/Dropbox/dev/pycharm/p056 gensim explore/main.py", line 13, in <module>
    main()
  File "/Users/bruceschechter/Dropbox/dev/pycharm/p056 gensim explore/main.py", line 8, in main
    model = Doc2Vec.load('doc2vec.bin')
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/models/doc2vec.py", line 813, in load
    raise ae
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/models/doc2vec.py", line 807, in load
    return super(Doc2Vec, cls).load(*args, rethrow=True, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/models/word2vec.py", line 1937, in load
    raise ae
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/models/word2vec.py", line 1930, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/utils.py", line 485, in load
    obj = unpickle(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/gensim/utils.py", line 1460, in unpickle
    return _pickle.load(f, encoding='latin1')  # needed because loading from S3 doesn't support readline()
AttributeError: Can't get attribute 'DocvecsArray' on <module 'gensim.models.doc2vec' from '/opt/homebrew/lib/python3.9/site-packages/gensim/models/doc2vec.py'>

My config...
MBPro M1, MacOS 12.3.1
Python 3.9.12. (via Homebrew)
pip 22.0.4
Gensim 4.1.2

Thanks!

**Comment by jhlau** [comment]
You should use python2 and my forked version of gensim (see README).

**Comment by bruceschek** [comment]
thanks for quick response!
